id: IE9CAF5ED
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T03:28:51+00:00'
last_modified: '2022-06-08T05:44:30.776308+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG17575
  title: དཔལ་ཀྱཻ་རྡོ་རྗེའི་དབང་གི་ཆུ་བོ་ཆེན་མོ་མཛེས་པར་བྱེད་པའི་རྒྱན་ནག་འགྲོས་བཀླག་ཆོག་ཏུ་བཀོད་པ་སྭ་ར་སྭ་སྟིའི་ཀླུང་ཆེན་བདུད་རྩིའི་རྒྱུན་འབབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    894F:
      image_group_id: I1KG17934
      title: ''
      total_pages: 146
      order: 1
      base_file: 894F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
